create database examenPrueba;
use examenPrueba;
create table Alumnos (
DNI varchar(11),
Nombre varchar(10),
Apellido varchar(10),
Edad int,
Ciudad varchar(10)
);
create table Productos (
DNI varchar(11),
NumProductos int
);
INSERT INTO Alumnos VALUES
('47657450-L','Jon','Zamora','29','Irun'),
('47657450-L','Jon','Zamora','29','Madrid'),
('42000201-T','Daniel','García','31','Cancun'),
('32120101-F','Fernando','López','19','Madrid'),
('10000000-R','Ramiro','Ramiro','21','Bilbao'),
('10000000-R','Ramiro','Ramiro','21','Barcelona'),
('44566812-M','Marius','Mario','20','Irun');
INSERT INTO Productos VALUES
('47657450-L','4'),
('44566812-M','1'),
('42000201-T','0'),
('32120101-F','0'),
('10000000-R','2');

Ejercicio 1
SELECT *
FROM ALUMNOS AS A INNER JOIN PRODUCTOS AS P ON A.DNI=P.DNI 
ORDER BY A.NOMBRE;
Ejercicio 2
SELECT AVG (A.EDAD) AS MediaEdad 
FROM ALUMNOS AS A INNER JOIN PRODUCTOS AS P ON A.DNI=P.DNI;
Ejercicio 3
SELECT A.*
FROM ALUMNOS AS A INNER JOIN PRODUCTOS AS P ON A.DNI=P.DNI
WHERE A.NOMBRE LIKE "j%" AND A.APELLIDO LIKE "%a%";
Ejercio 4
SELECT A.*
FROM ALUMNOS AS A INNER JOIN PRODUCTOS AS P ON A.DNI=P.DNI
WHERE A.CIUDAD IN ("IRUN", "MADRID", "BILBAO");
Ejercicio 5
SELECT DISTINCT A.NOMBRE,A.EDAD,A.APELLIDO  
FROM ALUMNOS AS A INNER JOIN PRODUCTOS AS P ON A.DNI=P.DNI
ORDER BY A.EDAD DESC;
Ejercico 6
SELECT count(distinct A.NOMBRE) AS NUMALUMNOS
FROM PRODUCTOS AS P INNER JOIN ALUMNOS AS A ON P.DNI=A.DNI;

Ejercicio 7
SELECT distinct A.NOMBRE, P.NUMPRODUCTOS
FROM PRODUCTOS AS P INNER JOIN ALUMNOS AS A ON P.DNI=A.DNI
WHERE P.NUMPRODUCTOS >= 1;

Ejercicio 8
SELECT A.NOMBRE
FROM PRODUCTOS AS P INNER JOIN ALUMNOS AS A ON P.DNI=A.DNI
WHERE A.EDAD BETWEEN 23 AND 28;

Ejercicio 9
SELECT DISTINCT DNI, NOMBRE, APELLIDO
FROM ALUMNOS;

Ejercicio 10
SELECT MAX(P.NUMPRODUCTOS) AS NUMMAX, MIN(P.NUMPRODUCTOS) AS NUMMIN
FROM PRODUCTOS AS P INNER JOIN ALUMNOS AS A ON P.DNI=A.DNI;